folder_tst: /home/georgy/tst
folder_in: /home/georgy/tst/file
folder_out: /home/georgy/tst/out
folder_ext: /home/georgy/tst/ext
folder_ext2: /home/georgy/tst/ext2
folder_badarx: /home/georgy/tst/badarx
filename: res.txt
folder_out_negative: /home/georgy/tst/badarx
count: 5
bs: 1M
host: 0.0.0.0
user: user2
password: "111"
local_path: /home/georgy/p7zip-full.deb
remote_path: /home/user2/p7zip-full.deb
pkgname: p7zip-full
stat_loadavg: /proc/loadavg
type_7z: "-tzip"